name: Dataset submission
description: Submit a dataset for review and inclusion in the Pointers collection
title: "[Dataset submission]: "
labels: ["dataset-submission"]
assignees:
  - tobyhodges
  - vantuyls
body:
  - type: markdown
    attributes:
      value: |
        Thank you for your interest in submitting a dataset to Pointers!
        Please respond to the prompts below to complete your submission,
        referring to the Inclusion Requirements & Guidance section of this
        repository's README[1] as you do so.
        Check boxes by adding an 'x' between the square brackets at the start of each point
        (i.e. [x]),
        or submit the issue and check off the boxes afterwards.
        
        [1]: https://github.com/carpentries/pointers#inclusion-requirements-and-guidance
  - type: input
    id: name
    attributes:
      label: Dataset Name
      description: What is the name of the dataset record in Zenodo?
      placeholder: ex. Weather Prediction Dataset
    validations:
      required: true
  - type: input
    id: zenodo-url
    attributes:
      label: Zenodo Entry URL
      description: What is the URL of the dataset record in Zenodo?
      placeholder: ex. https://zenodo.org/record/7525955
    validations:
      required: true
  - type: input
    id: format
    attributes:
      label: Dataset format(s)
      description: What is the format of the dataset?
      placeholder: ex. plain text files, Jupyter notebook files, image files, database files
    validations:
      required: true
  - type: checkboxes
    id: terms
    attributes:
      label: Confirmation of Dataset Requirements
      description: 'Check the boxes to confirm that the dataset record includes:'
      options:
        - label: a README file describing the dataset
          required: true
        - label: a license file or folder of license files
          required: true
  - type: textarea
    id: supplementary-information
    attributes:
      label: Description of Supplementary Information
      description: If the dataset record includes supplementary information such as teaching materials or code, please briefly describe these.
